export const NAME_TABLE_ENTITY = "Entity";
export const NAME_TABLE_ENTITY__ID = "Entity_ID";
export const NAME_TABLE_ENTITY__ENTITY_NAME = "EntityName";
export const NAME_TABLE_ENTITY__SCHEMA = "Schema";

export const NAME_TABLE_COLUMN = "Column";
export const NAME_TABLE_COLUMN__ID = "Column_ID";
export const NAME_TABLE_COLUMN__COLUMN_NAME = "ColumnName";
export const NAME_TABLE_COLUMN__TYPE = "Type";
export const NAME_TABLE_COLUMN__ORIGINAL_TYPE = "OriginalType";
export const NAME_TABLE_COLUMN__AUTO_INCREMENT = "AutoIncrement";
export const NAME_TABLE_COLUMN__UNIQUE = "Unique";
export const NAME_TABLE_COLUMN__BYTES = "Bytes";
export const NAME_TABLE_COLUMN__SIZE = "Size";
export const NAME_TABLE_COLUMN__NULLEABLE = "Nulleable";
export const NAME_TABLE_COLUMN__PRESITION = "Presition";
export const NAME_TABLE_COLUMN__SCALE = "Scale";
export const NAME_TABLE_COLUMN__TIME_ZONE = "TimeZone";
export const NAME_TABLE_COLUMN__DEFAULT = "Default";

export const NAME_TABLE_UNIQUE = "Unique";
export const NAME_TABLE_UNIQUE__ID = "Unique_ID";
export const NAME_TABLE_UNIQUE__UNIQUE_NAME = "UniqueName";
export const NAME_TABLE_UNIQUE__COLUMN_IDS = "ColumnIds";
export const NAME_TABLE_UNIQUE__COLUMN_NAMES = "ColumnNames";

/**
 * CREATES
 */

export const QUERY_CREATE_ENTITY = `
CREATE TABLE IF NOT EXISTS ${NAME_TABLE_ENTITY} (
  ${NAME_TABLE_ENTITY__ID} INTEGER PRIMARY KEY AUTOINCREMENT,
  ${NAME_TABLE_ENTITY__ENTITY_NAME} TEXT,
  ${NAME_TABLE_ENTITY__SCHEMA} TEXT
)
`;

export const QUERY_CREATE_COLUMN = `
CREATE TABLE IF NOT EXISTS ${NAME_TABLE_COLUMN} (
  ${NAME_TABLE_COLUMN__ID} INTEGER PRIMARY KEY AUTOINCREMENT,
  ${NAME_TABLE_ENTITY__ID} INTEGER,
  ${NAME_TABLE_COLUMN__COLUMN_NAME} TEXT,
  ${NAME_TABLE_COLUMN__TYPE} TEXT,
  ${NAME_TABLE_COLUMN__ORIGINAL_TYPE} TEXT,
  "${NAME_TABLE_COLUMN__AUTO_INCREMENT}" INTEGER,
  "${NAME_TABLE_COLUMN__UNIQUE}" INTEGER,
  ${NAME_TABLE_COLUMN__BYTES} INTEGER,
  ${NAME_TABLE_COLUMN__SIZE} INTEGER,
  ${NAME_TABLE_COLUMN__NULLEABLE} INTEGER,
  ${NAME_TABLE_COLUMN__PRESITION} INTEGER,
  ${NAME_TABLE_COLUMN__SCALE} INTEGER,
  ${NAME_TABLE_COLUMN__TIME_ZONE} INTEGER,
  "${NAME_TABLE_COLUMN__DEFAULT}" INTEGER
)
`;

export const QUERY_CREATE_UNIQUE = `
CREATE TABLE IF NOT EXISTS "${NAME_TABLE_UNIQUE}" (
  ${NAME_TABLE_UNIQUE__ID} INTEGER PRIMARY KEY AUTOINCREMENT,
  ${NAME_TABLE_ENTITY__ID} INTEGER,
  ${NAME_TABLE_UNIQUE__UNIQUE_NAME} TEXT,
  ${NAME_TABLE_UNIQUE__COLUMN_IDS} TEXT,
  ${NAME_TABLE_UNIQUE__COLUMN_NAMES} TEXT
)
`;

/**
 * INSERTS
 */

export const QUERY_INSERT_ENTITY = `
INSERT INTO ${NAME_TABLE_ENTITY} (
  ${NAME_TABLE_ENTITY__ENTITY_NAME},
  ${NAME_TABLE_ENTITY__SCHEMA}
)
VALUES (
  :${NAME_TABLE_ENTITY__ENTITY_NAME},
  :${NAME_TABLE_ENTITY__SCHEMA}
)
`;

export const QUERY_INSERT_COLUMN = `
INSERT INTO ${NAME_TABLE_COLUMN} (
  ${NAME_TABLE_ENTITY__ID},
  ${NAME_TABLE_COLUMN__COLUMN_NAME},
  ${NAME_TABLE_COLUMN__TYPE},
  ${NAME_TABLE_COLUMN__ORIGINAL_TYPE},
  "${NAME_TABLE_COLUMN__AUTO_INCREMENT}",
  "${NAME_TABLE_COLUMN__UNIQUE}",
  ${NAME_TABLE_COLUMN__BYTES},
  ${NAME_TABLE_COLUMN__SIZE},
  ${NAME_TABLE_COLUMN__NULLEABLE},
  ${NAME_TABLE_COLUMN__PRESITION},
  ${NAME_TABLE_COLUMN__SCALE},
  ${NAME_TABLE_COLUMN__TIME_ZONE},
  "${NAME_TABLE_COLUMN__DEFAULT}"
)
VALUES (
  :${NAME_TABLE_ENTITY__ID},
  :${NAME_TABLE_COLUMN__COLUMN_NAME},
  :${NAME_TABLE_COLUMN__TYPE},
  :${NAME_TABLE_COLUMN__ORIGINAL_TYPE},
  :${NAME_TABLE_COLUMN__AUTO_INCREMENT},
  :${NAME_TABLE_COLUMN__UNIQUE},
  :${NAME_TABLE_COLUMN__BYTES},
  :${NAME_TABLE_COLUMN__SIZE},
  :${NAME_TABLE_COLUMN__NULLEABLE},
  :${NAME_TABLE_COLUMN__PRESITION},
  :${NAME_TABLE_COLUMN__SCALE},
  :${NAME_TABLE_COLUMN__TIME_ZONE},
  :${NAME_TABLE_COLUMN__DEFAULT}
)
`;

export const QUERY_INSERT_UNIQUE = `
INSERT INTO "${NAME_TABLE_UNIQUE}" (
  ${NAME_TABLE_ENTITY__ID},
  ${NAME_TABLE_UNIQUE__UNIQUE_NAME},
  ${NAME_TABLE_UNIQUE__COLUMN_IDS},
  ${NAME_TABLE_UNIQUE__COLUMN_NAMES}
)
VALUES (
  :${NAME_TABLE_ENTITY__ID},
  :${NAME_TABLE_UNIQUE__UNIQUE_NAME},
  :${NAME_TABLE_UNIQUE__COLUMN_IDS},
  :${NAME_TABLE_UNIQUE__COLUMN_NAMES}
)
`;

export const QUERY_SELECT_ENTITY = `
SELECT ${NAME_TABLE_ENTITY__ID}
  , ${NAME_TABLE_ENTITY__ENTITY_NAME}
	, ${NAME_TABLE_ENTITY__SCHEMA}
FROM ${NAME_TABLE_ENTITY}
`;

export const QUERY_SELECT_COLUMN = `
SELECT ${NAME_TABLE_COLUMN__ID}
  , ${NAME_TABLE_ENTITY__ID}
  , ${NAME_TABLE_COLUMN__COLUMN_NAME}
  , ${NAME_TABLE_COLUMN__TYPE}
  , ${NAME_TABLE_COLUMN__ORIGINAL_TYPE}
  , "${NAME_TABLE_COLUMN__AUTO_INCREMENT}"
  , "${NAME_TABLE_COLUMN__UNIQUE}"
  , ${NAME_TABLE_COLUMN__BYTES}
  , ${NAME_TABLE_COLUMN__SIZE}
  , ${NAME_TABLE_COLUMN__NULLEABLE}
  , ${NAME_TABLE_COLUMN__PRESITION}
  , ${NAME_TABLE_COLUMN__SCALE}
  , ${NAME_TABLE_COLUMN__TIME_ZONE}
  , "${NAME_TABLE_COLUMN__DEFAULT}"
FROM ${NAME_TABLE_COLUMN}
`;

export const QUERY_SELECT_UNIQUE = `
SELECT ${NAME_TABLE_UNIQUE__ID}
  , ${NAME_TABLE_ENTITY__ID}
  , ${NAME_TABLE_UNIQUE__UNIQUE_NAME}
	, ${NAME_TABLE_UNIQUE__COLUMN_IDS}
	, ${NAME_TABLE_UNIQUE__COLUMN_NAMES}
FROM "${NAME_TABLE_UNIQUE}"
`;

export const QUERY_SELECT_ENTITY_LAST_INSERT = `
${QUERY_SELECT_ENTITY}
WHERE ${NAME_TABLE_ENTITY__ID} = LAST_INSERT_ROWID()
`;

export const QUERY_SELECT_COLUMN_LAST_INSERT = `
${QUERY_SELECT_COLUMN}
WHERE ${NAME_TABLE_COLUMN__ID} = LAST_INSERT_ROWID()
`;

export const QUERY_SELECT_UNIQUE_LAST_INSERT = `
${QUERY_SELECT_UNIQUE}
WHERE ${NAME_TABLE_UNIQUE__ID} = LAST_INSERT_ROWID()
`;

const all = {
  QUERY_CREATE_ENTITY,
  QUERY_CREATE_COLUMN,
  QUERY_CREATE_UNIQUE,

  QUERY_SELECT_ENTITY,
  QUERY_SELECT_ENTITY_LAST_INSERT,
  QUERY_SELECT_COLUMN,
  QUERY_SELECT_COLUMN_LAST_INSERT,
  QUERY_SELECT_UNIQUE,
  QUERY_SELECT_UNIQUE_LAST_INSERT,

  QUERY_INSERT_ENTITY,
  QUERY_INSERT_COLUMN,
  QUERY_INSERT_UNIQUE,

  NAME_TABLE_ENTITY,
  NAME_TABLE_ENTITY__ID,
  NAME_TABLE_ENTITY__ENTITY_NAME,
  NAME_TABLE_ENTITY__SCHEMA,

  NAME_TABLE_COLUMN,
  NAME_TABLE_COLUMN__ID,
  NAME_TABLE_COLUMN__COLUMN_NAME,
  NAME_TABLE_COLUMN__TYPE,
  NAME_TABLE_COLUMN__ORIGINAL_TYPE,
  NAME_TABLE_COLUMN__AUTO_INCREMENT,
  NAME_TABLE_COLUMN__UNIQUE,
  NAME_TABLE_COLUMN__BYTES,
  NAME_TABLE_COLUMN__SIZE,
  NAME_TABLE_COLUMN__NULLEABLE,
  NAME_TABLE_COLUMN__PRESITION,
  NAME_TABLE_COLUMN__SCALE,
  NAME_TABLE_COLUMN__TIME_ZONE,
  NAME_TABLE_COLUMN__DEFAULT,

  NAME_TABLE_UNIQUE,
  NAME_TABLE_UNIQUE__ID,
  NAME_TABLE_UNIQUE__UNIQUE_NAME,
  NAME_TABLE_UNIQUE__COLUMN_IDS,
  NAME_TABLE_UNIQUE__COLUMN_NAMES,
};

const queries = {
  CREATE_ENTITY: all.QUERY_CREATE_ENTITY,
  CREATE_COLUMN: all.QUERY_CREATE_COLUMN,
  CREATE_UNIQUE: all.QUERY_CREATE_UNIQUE,

  INSERT_ENTITY: all.QUERY_INSERT_ENTITY,
  INSERT_COLUMN: all.QUERY_INSERT_COLUMN,
  INSERT_UNIQUE: all.QUERY_INSERT_UNIQUE,

  SELECT_ENTITY: all.QUERY_SELECT_ENTITY,
  SELECT_ENTITY_LAST_INSERT: all.QUERY_SELECT_ENTITY_LAST_INSERT,
  SELECT_COLUMN: all.QUERY_SELECT_COLUMN,
  SELECT_COLUMN_LAST_INSERT: all.QUERY_SELECT_COLUMN_LAST_INSERT,
  SELECT_UNIQUE: all.QUERY_SELECT_UNIQUE,
  SELECT_UNIQUE_LAST_INSERT: all.QUERY_SELECT_UNIQUE_LAST_INSERT,
};
const names = {
  TABLE_ENTITY: all.NAME_TABLE_ENTITY,
  TABLE_ENTITY__ID: all.NAME_TABLE_ENTITY__ID,
  TABLE_ENTITY__ENTITY_NAME: all.NAME_TABLE_ENTITY__ENTITY_NAME,
  TABLE_ENTITY__SCHEMA: all.NAME_TABLE_ENTITY__SCHEMA,

  TABLE_COLUMN: all.NAME_TABLE_COLUMN,
  TABLE_COLUMN__ID: all.NAME_TABLE_COLUMN__ID,
  TABLE_COLUMN__COLUMN_NAME: all.NAME_TABLE_COLUMN__COLUMN_NAME,
  TABLE_COLUMN__TYPE: all.NAME_TABLE_COLUMN__TYPE,
  TABLE_COLUMN__ORIGINAL_TYPE: all.NAME_TABLE_COLUMN__ORIGINAL_TYPE,
  TABLE_COLUMN__AUTO_INCREMENT: all.NAME_TABLE_COLUMN__AUTO_INCREMENT,
  TABLE_COLUMN__UNIQUE: all.NAME_TABLE_COLUMN__UNIQUE,
  TABLE_COLUMN__BYTES: all.NAME_TABLE_COLUMN__BYTES,
  TABLE_COLUMN__SIZE: all.NAME_TABLE_COLUMN__SIZE,
  TABLE_COLUMN__NULLEABLE: all.NAME_TABLE_COLUMN__NULLEABLE,
  TABLE_COLUMN__PRESITION: all.NAME_TABLE_COLUMN__PRESITION,
  TABLE_COLUMN__SCALE: all.NAME_TABLE_COLUMN__SCALE,
  TABLE_COLUMN__TIME_ZONE: all.NAME_TABLE_COLUMN__TIME_ZONE,
  TABLE_COLUMN__DEFAULT: all.NAME_TABLE_COLUMN__DEFAULT,

  TABLE_UNIQUE: all.NAME_TABLE_UNIQUE,
  TABLE_UNIQUE__ID: all.NAME_TABLE_UNIQUE__ID,
  TABLE_UNIQUE__UNIQUE_NAME: all.NAME_TABLE_UNIQUE__UNIQUE_NAME,
  TABLE_UNIQUE__COLUMN_IDS: all.NAME_TABLE_UNIQUE__COLUMN_IDS,
  TABLE_UNIQUE__COLUMN_NAMES: all.NAME_TABLE_UNIQUE__COLUMN_NAMES,
};

export default { ...all, queries, names };
